# Generated by Django 4.0.3 on 2022-04-04 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.SmallIntegerField()),
                ('age', models.SmallIntegerField()),
                ('born_in', models.SmallIntegerField()),
                ('lived_in', models.SmallIntegerField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialects.case')),
            ],
        ),
    ]
